blueprint:
  name: Voice - AI Image Generator with Reference Image (Simplified)
  author: TriTue2011
  description: 'Tool for generating images using AI based on a reference image and text descriptions.'
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    ai_task_settings:
      name: Settings for AI Task
      icon: mdi:robot-outline
      description: 'These settings allow you to set up the AI Task responsible for handling the image generation task.'
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          description: 'If left empty, the system will use the default settings under System - General. Make sure to select an AI Task that supports image generation with reference images.'
          selector:
            entity:
              filter:
              - domain:
                - ai_task
              multiple: false
              reorder: false
          default:
    output_settings:
      name: Settings for Image Output
      icon: mdi:folder-image
      description: 'Configure where generated images should be stored and how filenames are generated.'
      collapsed: true
      input:
        output_directory:
          name: Output Directory
          description: 'Absolute path where the generated image will be stored (default is /media).'
          selector:
            text:
              multiple: false
              multiline: false
          default: /media
        filename_prefix:
          name: Filename Prefix
          description: 'Prefix used when generating the image filename.'
          selector:
            text:
              multiple: false
              multiline: false
          default: ai_generated_ref_
        file_extension:
          name: File Extension
          description: 'File extension to use for the generated image (for example jpg or png).'
          selector:
            text:
              multiple: false
              multiline: false
          default: png
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: 'You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.'
      collapsed: true
      input:
        instructions_prompt:
          name: Instructions Prompt
          description: 'The prompt used for the LLM to describe the image generation request with additional styling or context.'
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is mandatory and must always be provided.

            Describe what changes or enhancements you want to apply to the reference image. You can specify new backgrounds, clothing, accessories, lighting, artistic styles.

            Examples:
            - "Change the background to a luxury office, person wearing designer glasses"
            - "Transform to professional headshot with studio lighting"
            - "Place person in a beach setting with sunset lighting, make outfit casual"

            Note: The face, facial features, smile, skin tone, and hair from the reference image will ALWAYS be preserved exactly unless preservation mode requests otherwise.'
        media_path_prompt:
          name: Media Path Prompt
          description: 'The prompt which will be used for the LLM to provide the reference image path.'
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is mandatory and must always be provided.

            Always provide a media path that starts with `local/` (for example `local/photos/person.jpg` or `local/images/face.png`).

            This should be the path to the reference image whose face and identity will be preserved.'
        mime_type_prompt:
          name: MIME Type Prompt
          description: 'The prompt which will be used for the LLM to provide the MIME type of the reference image.'
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is mandatory and must always be provided.

            Always specify the MIME type of the reference image. Typically this should be image/jpeg or image/png.'
        task_name_prompt:
          name: Task Name Prompt
          description: 'The prompt for the LLM to provide a short and descriptive task name for the image generation.'
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is optional.

            Provide a short, natural, and descriptive task name for the image generation request.

            The name should reflect what you''re generating (for example "Professional Portrait with Glasses", "Beach Sunset Portrait", "Formal Office Setting").

            If not provided, the name will be auto-generated based on the instructions.'
        preservation_mode_prompt:
          name: Preservation Mode Prompt
          description: 'The prompt for selecting what elements to preserve from the reference image.'
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is optional.

            Specify what you want to preserve from the reference image:

            - "face" (default): Preserve face, facial features, skin tone, hair
            - "product": Preserve product shape, color, texture, brand details
            - "accessory": Preserve accessories like bags, glasses, jewelry with original colors and design
            - "clothing": Preserve clothing items with fabric texture, color, pattern
            - "all": Preserve everything from reference image

            If not specified, defaults to "face" mode.'
  source_url: https://raw.githubusercontent.com/TriTue2011/Blueprint/main/ai_image_attrack.yaml
mode: parallel
max: 10
max_exceeded: silent
variables:
  version: 20251205
fields:
  instructions:
    name: Instructions
    description: !input instructions_prompt
    selector:
      text:
        multiline: true
    required: true
  media_path:
    name: Reference Image Path
    description: !input media_path_prompt
    selector:
      text:
    required: true
  mime_type:
    name: MIME Type
    description: !input mime_type_prompt
    selector:
      text:
    required: true
  task_name:
    name: Task Name
    description: !input task_name_prompt
    selector:
      text:
    required: false
  preservation_mode:
    name: Preservation Mode
    description: !input preservation_mode_prompt
    selector:
      select:
        options:
        - label: Face (Default)
          value: face
        - label: Product
          value: product
        - label: Accessory
          value: accessory
        - label: Clothing
          value: clothing
        - label: All Elements
          value: all
    required: false
sequence:
- variables:
    ai_task_entity: !input ai_task_entity
    instructions_input: '{{ instructions | default("") | trim }}'
    media_path: '{{ media_path | default("") | trim }}'
    mime_type: '{{ mime_type | default("") | trim }}'
    task_name_input: '{{ task_name | default("") | trim }}'
    preservation_mode: '{{ preservation_mode | default("face") | trim }}'
- alias: Validate instructions
  if:
  - condition: template
    value_template: '{{ not instructions_input }}'
  then:
  - alias: Set variable for error message
    variables:
      response:
        error: Unable to generate image because instructions are missing or empty.
  - alias: Stop the script
    stop: Unable to generate image because instructions are missing or empty.
    response_variable: response
- alias: Validate media path
  if:
  - condition: template
    value_template: '{{ (media_path | length == 0) or (not media_path.startswith("local/")) }}'
  then:
  - alias: Set variable for error message
    variables:
      response:
        error: Unable to generate image because reference image path is missing or invalid. Provide a path beginning with `local/`, such as `local/folder/image.jpg`.
  - alias: Stop the script
    stop: Unable to generate image because reference image path is missing or invalid.
    response_variable: response
- alias: Validate MIME type
  if:
  - condition: template
    value_template: '{{ not mime_type.startswith("image/") }}'
  then:
  - alias: Set variable for error message
    variables:
      response:
        error: Unable to generate image because MIME type is missing or incorrect. Must be an image type (image/jpeg, image/png, etc.).
  - alias: Stop the script
    stop: Unable to generate image because MIME type is missing or incorrect.
    response_variable: response
- variables:
    strict_change_control: 'QUY TẮC VÀNG - TUYỆT ĐỐI KHÔNG TỰ Ý THAY ĐỔI: CHỈ thay đổi CHÍNH XÁC những gì được yêu cầu trong instructions. Nếu yêu cầu "thêm kính" thì CHỈ thêm kính, KHÔNG được tự ý thay đổi trang phục, tóc, tư thế, nền, ánh sáng hay bất kỳ yếu tố nào khác. Nếu yêu cầu "đổi nền" thì CHỈ đổi nền, giữ nguyên tất cả các yếu tố khác. Nếu yêu cầu "thay áo" thì CHỉ thay áo, giữ nguyên tất cả các yếu tố khác. NGHIÊM CẤM thêm, bớt, hoặc điều chỉnh bất kỳ chi tiết nào không được đề cập rõ ràng trong yêu cầu. STRICT RULE: ONLY change what is EXPLICITLY requested in the instructions. If the request says "add glasses", ONLY add glasses - DO NOT change clothing, hair, pose, background, lighting, or any other element. If it says "change background", ONLY change background - keep everything else identical. If it says "change shirt", ONLY change shirt - preserve all other elements. FORBIDDEN to add, remove, or modify any detail not explicitly mentioned in the request. Do not make creative additions or improvements unless specifically asked.'
    mandatory_prompt: 'QUAN TRỌNG TỐI CAO, LỆNH BẮT BUỘC: Giữ nguyên 100% khuôn mặt, nét mặt, nụ cười, màu da, và mái tóc từ ảnh gốc. TUYỆT ĐỐI KHÔNG thay đổi bất kỳ đặc điểm, danh tính hay biểu cảm nào. CỰC KỲ QUAN TRỌNG: Mọi chi tiết độc nhất như sẹo, nốt ruồi, mụn, nếp nhăn, và kết cấu da PHẢI được giữ lại y hệt. Khuôn mặt đã được khóa hoàn toàn. Chỉ thay đổi bối cảnh, trang phục và phong cách. face lock, identity lock, high fidelity face, do not change face, keep original face, skin texture must be preserved, all marks like acne, scars, moles must be kept. 16K ultra-high definition, masterpiece, professional photography. Avoid the following: blurriness, low resolution, overexposure, underexposure, distorted faces, extra fingers, distorted hands, incorrect anatomy, unnatural poses, doll-like skin, plastic textures, cartoons, oversaturated colors, flat lighting, grain, noise, watermarks, text, logos, duplicated objects, cropped body parts, unrealistic shadows, floating objects.'
    face_lock_instruction: 'QUAN TRỌNG TỐI CAO - LỆNH BẮT BUỘC GIỮ KHUÔN MẶT: Giữ nguyên 100% khuôn mặt, nét mặt, nụ cười, màu da, và mái tóc từ ảnh gốc. TUYỆT ĐỐI KHÔNG thay đổi bất kỳ đặc điểm, danh tính hay biểu cảm nào. CỰC KỲ QUAN TRỌNG: Mọi chi tiết độc nhất như sẹo, nốt ruồi, mụn, nếp nhăn, và kết cấu da PHẢI được giữ lại y hệt. Khuôn mặt đã được khóa hoàn toàn. face lock, identity lock, high fidelity face, do not change face, keep original face exactly, skin texture must be preserved, all marks like acne, scars, moles must be kept, facial expression locked.'
    product_lock_instruction: 'QUAN TRỌNG - GIỮ NGUYÊN CON NGƯỜI VÀ SẢN PHẨM: Giữ nguyên 100% khuôn mặt, hình dáng cơ thể của con người. Đồng thời giữ nguyên sản phẩm trong ảnh (hình dáng, màu sắc, logo, nhãn hiệu). Có thể thay đổi: bối cảnh, ánh sáng, góc chụp, hiệu ứng. preserve person identity and body shape, keep product original, flexible background and lighting.'
    accessory_lock_instruction: 'QUAN TRỌNG - GIỮ NGUYÊN CON NGƯỜI VÀ PHỤ KIỆN: Giữ nguyên 100% khuôn mặt, hình dáng cơ thể của con người. Đồng thời giữ nguyên các phụ kiện chính (túi xách, kính mắt, trang sức, đồng hồ - màu sắc, thiết kế, logo). Có thể thay đổi: bối cảnh, trang phục, ánh sáng, tư thế. preserve person identity and body shape, keep accessories original, flexible clothing and background.'
    clothing_lock_instruction: 'QUAN TRỌNG - GIỮ NGUYÊN CON NGƯỜI VÀ TRANG PHỤC: Giữ nguyên 100% khuôn mặt, hình dáng cơ thể của con người. Đồng thời giữ nguyên trang phục đang mặc (màu sắc, kiểu dáng, họa tiết, logo). Có thể thay đổi: bối cảnh, phụ kiện, ánh sáng, tư thế. preserve person identity and body shape, keep clothing original, flexible accessories and background.'
    all_elements_instruction: 'QUAN TRỌNG TỐI CAO - CHUYỂN ĐỔI BỐI CẢNH: Giữ nguyên 100% khuôn mặt và hình dáng cơ thể của con người. CHỈ thay đổi bối cảnh, môi trường xung quanh. Có thể điều chỉnh: ánh sáng, màu sắc tổng thể, không khí của ảnh để phù hợp bối cảnh mới. preserve person identity and body shape completely, change only background and environment, adjust lighting to match new scene.'
    preservation_instruction: "{% if preservation_mode == \"product\" %}\n  {{ product_lock_instruction }}\n{% elif preservation_mode == \"accessory\" %}\n  {{ accessory_lock_instruction }}\n{% elif preservation_mode == \"clothing\" %}\n  {{ clothing_lock_instruction }}\n{% elif preservation_mode == \"all\" %}\n  {{ all_elements_instruction }}\n{% else %}\n  {{ face_lock_instruction }}\n{% endif %}"
    full_instructions: '{{ strict_change_control }} {{ mandatory_prompt }} {{ preservation_instruction }} {{ instructions_input }}'
    auto_task_name: "{% if task_name_input %}\n  {{ task_name_input }}\n{% else %}\n  {% set words = instructions_input.split()[:6] %}\n  {{ words | join(' ') | truncate(80, True, '') }}\n{% endif %}"
    attachments:
      media_content_id: media-source://media_source/{{ media_path }}
      media_content_type: '{{ mime_type }}'
- alias: Generate image using AI Task
  if:
  - condition: template
    value_template: '{{ not ai_task_entity }}'
  then:
  - action: ai_task.generate_image
    data:
      task_name: '{{ auto_task_name }}'
      instructions: '{{ full_instructions }}'
      attachments: '{{ attachments }}'
    response_variable: ai_result
  else:
  - action: ai_task.generate_image
    data:
      task_name: '{{ auto_task_name }}'
      instructions: '{{ full_instructions }}'
      attachments: '{{ attachments }}'
      entity_id: '{{ ai_task_entity }}'
    response_variable: ai_result
- alias: Check if image generation was successful
  if:
  - condition: template
    value_template: '{{ ai_result is defined and ai_result.media_source_id is defined }}'
  then:
  - variables:
      image_path_from_media_source: "{% set source_id = ai_result.media_source_id %} {% if source_id.startswith('media-source://ai_task/image/') %}\n  {{ '/media/ai_task/image/' ~ source_id.split('/')[-1] }}\n{% else %}\n  {{ source_id }}\n{% endif %}"
      response:
        image_path: '{{ image_path_from_media_source }}'
        task_name: '{{ auto_task_name }}'
        instructions: '{{ full_instructions }}'
        reference_image: '{{ media_path }}'
        preservation_mode: '{{ preservation_mode }}'
        status: Image generated successfully with {{ preservation_mode }} preservation
        media_source_id: '{{ ai_result.media_source_id }}'
        url: '{{ ai_result.url | default("") }}'
        model: '{{ ai_result.model | default("") }}'
        revised_prompt: '{{ ai_result.revised_prompt | default("") }}'
  else:
  - alias: Set error response
    variables:
      response:
        error: Image generation failed. The AI Task did not return a valid image URL.
  - alias: Stop script with error
    stop: Image generation failed. The AI Task did not return a valid image URL.
    response_variable: response
- stop: ''
  response_variable: response
