blueprint:
  name: Voice - Capture Camera Snapshot
  author: luuquangvu
  description: "# Tool for capturing camera snapshots used for Voice Assistant\n##
    Blueprint Setup\n### Required\n* A template sensor stores all information about
    entity aliases needs to be configured in `config/configuration.yaml`; The sensor
    is required for friendly-name lookup.\n```\n#File configuration.yaml\nshell_command:\n
    \ get_entity_alias: jq '[.data.entities[] | select(.options.conversation.should_expose
    == true and (.aliases | length > 0)) | {entity_id, aliases}]' ./.storage/core.entity_registry\ntemplate:\n
    \ - triggers:\n      - trigger: homeassistant\n        event: start\n      - trigger:
    event\n        event_type: event_template_reloaded\n    actions:\n      - action:
    shell_command.get_entity_alias\n        response_variable: response\n    sensor:\n
    \     - name: \"Assist: Entity IDs and Aliases\"\n        unique_id: entity_ids_and_aliases\n
    \       icon: mdi:format-list-bulleted\n        device_class: timestamp\n        state:
    \"{{ now().isoformat() }}\"\n        attributes:\n          entities: \"{{ response.stdout
    }}\"\n\n```\n* Ensure the directory defined in the snapshot settings exists (default
    is `/media`).\n### Optional\n* Adjust the prompts for each field used in the script.
    The descriptions guide the LLM to provide the correct input.\n### Note\n* Provide
    a concise and precise description for the script. This will be utilized by the
    LLM to understand it should use this script for capturing a snapshot from a camera.\n*
    Make sure to expose camera entities to Assist.\n* Make sure to expose the script
    to Assist after the script has been saved.\n* Do not alter the default script
    name.\n* Once the script is created, click the three dots in the top right corner,
    choose \"Edit in YAML,\" and remove the `description: ...` line to restore the
    default. This step is important because it helps the LLM better understand the
    script's purpose."
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: You can use these settings to configure a template sensor that
        stores all information about entity aliases.
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
              - domain:
                - sensor
                integration: template
              multiple: false
              reorder: false
    snapshot_settings:
      name: Settings for Snapshot Output
      icon: mdi:folder-image
      description: Configure where snapshots should be stored and how filenames are
        generated.
      collapsed: true
      input:
        snapshot_directory:
          name: Snapshot Directory
          description: Absolute path where the snapshot will be stored (default is
            `/media`).
          selector:
            text:
              multiple: false
              multiline: false
          default: /media
        snapshot_filename_prefix:
          name: Snapshot Filename Prefix
          description: Prefix used when generating the snapshot filename.
          selector:
            text:
              multiple: false
              multiline: false
          default: camera_snapshot_
        snapshot_file_extension:
          name: Snapshot File Extension
          description: File extension to use for the snapshot (for example jpg or
            png).
          selector:
            text:
              multiple: false
              multiline: false
          default: jpg
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific
        LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        camera_name_prompt:
          name: Camera Name Prompt
          description: The prompt which will be used for the LLM can provide the camera
            name.
          selector:
            text:
              multiline: true
              multiple: false
          default: 'This argument is mandatory and must always be included.

            Specify the camera name to capture the snapshot from.

            Use the friendly name that appears in Home Assistant (for example "Front
            Door Camera").

            The tool will return a local file path to the generated snapshot.'
  source_url: https://github.com/luuquangvu/tutorials/blob/main/camera_snapshot_full_llm.yaml
mode: parallel
max_exceeded: silent
description: Takes a snapshot from a specified camera.
variables:
  version: 20251116
fields:
  camera_name:
    name: Camera Name
    description: !input camera_name_prompt
    selector:
      text:
    required: true
sequence:
- variables:
    entity_aliases: !input entity_aliases
    camera_name: '{{ camera_name | default('''') | trim }}'
    snapshot_directory_input: !input snapshot_directory
    snapshot_directory: '{{ snapshot_directory_input | default(''/media'', true) |
      trim }}'
    snapshot_prefix_input: !input snapshot_filename_prefix
    snapshot_prefix: '{{ snapshot_prefix_input | default(''camera_snapshot_'', true)
      | trim }}'
    snapshot_extension_input: !input snapshot_file_extension
    snapshot_extension: '{{ snapshot_extension_input | default(''jpg'', true) | trim
      | lower }}'
- alias: Validate camera name
  if:
  - condition: template
    value_template: '{% set friendly_match = states.camera | selectattr(''attributes.friendly_name'',
      ''=='', camera_name) | list %} {% set alias_match = state_attr(entity_aliases,
      ''entities'') | default([]) | selectattr(''entity_id'', ''match'', ''camera\.'')
      | selectattr(''aliases'', ''contains'', camera_name) | list %} {{ not camera_name
      or (friendly_match | length == 0 and alias_match | length == 0) }}'
  then:
  - alias: Set variable for error message
    variables:
      response:
        error: Unable to capture a snapshot because the camera name is invalid.
  - alias: Stop the script
    stop: Unable to capture a snapshot because the camera name is invalid.
    response_variable: response
- alias: Validate snapshot settings
  if:
  - condition: template
    value_template: '{{ not snapshot_directory }}'
  then:
  - alias: Set variable for error message
    variables:
      response:
        error: Unable to capture a snapshot because the snapshot directory is missing.
  - alias: Stop the script
    stop: Unable to capture a snapshot because the snapshot directory is missing.
    response_variable: response
- variables:
    camera_entity_id: "{% set friendly_match = states.camera | selectattr('attributes.friendly_name',
      '==', camera_name) | map(attribute='entity_id') | first %} {% if friendly_match
      %}\n  {{ friendly_match }}\n{% else %}\n  {{ state_attr(entity_aliases, 'entities')
      | default([]) | selectattr('entity_id', 'match', 'camera\\.') | selectattr('aliases',
      'contains', camera_name) | map(attribute='entity_id') | first }}\n{% endif %}"
    sanitized_prefix: "{% if snapshot_prefix %}\n  {{ snapshot_prefix | regex_replace('[^0-9A-Za-z_-]',
      '_') }}\n{% else %}\n  camera_snapshot_\n{% endif %}"
    sanitized_extension: "{% if snapshot_extension %}\n  {% set ext = snapshot_extension
      | regex_replace('[^0-9a-z]', '') %}\n  {{ '.' ~ (ext if ext else 'jpg') }}\n{%
      else %}\n  .jpg\n{% endif %}"
    snapshot_directory_normalized: "{% if snapshot_directory %}\n  {{ snapshot_directory.rstrip('/\\\\')
      }}\n{% else %}\n  /media\n{% endif %}"
    snapshot_random_suffix: '{{ ''%05d'' | format(range(0, 100000) | random) }}'
    snapshot_filename: '{{ sanitized_prefix ~ now().strftime(''%Y%m%d%H%M%S%f'') ~
      ''_'' ~ snapshot_random_suffix ~ sanitized_extension }}'
    snapshot_full_path: '{{ snapshot_directory_normalized ~ ''/'' ~ snapshot_filename
      }}'
    returned_image_path: "{% set prefix = '/media/' %} {% if snapshot_full_path.startswith(prefix)
      %}\n  {{ 'local/' ~ snapshot_full_path[prefix | length:] }}\n{% else %}\n  {{
      snapshot_full_path }}\n{% endif %}"
- action: camera.snapshot
  target:
    entity_id: '{{ camera_entity_id }}'
  data:
    filename: '{{ snapshot_full_path }}'
- variables:
    response:
      image_path: '{{ returned_image_path }}'
- stop: ''
  response_variable: response
