blueprint:
  name: Voice - Send to Telegram
  author: luuquangvu + merged
  source_url: https://github.com/luuquangvu/tutorials/blob/main/send_to_telegram_full_llm.yaml
  description: |-
    Tool for sending content to Telegram used for Voice Assistant.
    Supports information, location, and image.
    Resolves local/ image paths and optionally deletes images after sending.
  domain: script

  homeassistant:
    min_version: 2024.10.0

  input:
    telegram_settings:
      name: Settings for Telegram
      icon: mdi:send-circle
      input:
        chat_id:
          name: Chat ID
          description: Target chat or user to receive the message or image.
          selector:
            text:
        thread_id:
          name: Thread ID
          description: Thread (topic) where the message or image should be posted.
          selector:
            number:
              min: 1
              step: 1
          default:
        delete_after_send:
          name: Delete Image After Sending
          description: Automatically delete the image file after it has been sent.
          selector:
            boolean: {}
          default: true

    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      collapsed: true
      input:
        summary_prompt:
          name: Summary Prompt
          selector:
            text:
              multiline: true
          default: |-
            This argument is mandatory and must always be included.
            Provide a short summary (<=10 words).
            No markdown, emojis, or commentary.
            If content_type is image, write a concise caption.
            Return only plain text.

        detail_prompt:
          name: Detail Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional detailed information.
            No links, no markdown/emojis.
            Do not repeat the summary.
            Return only plain text.

        content_type_prompt:
          name: Content Type Prompt
          selector:
            text:
              multiline: true
          default: |-
            Mandatory.
            Return exactly one: information, location, image.
            Choose location for any place/map intent.
            Choose image when sending a photo with a path.
            Otherwise choose information.

        location_prompt:
          name: Location Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional. Use only when content_type is location.
            Return address name only.
            No punctuation.

        image_path_prompt:
          name: Image Path Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional. Use only when content_type is image.
            Provide an existing local/ or /media/ image path.
            Do not guess.

        chat_id_override_prompt:
          name: Chat ID Override Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional.
            Use only when user explicitly specifies another chat.
            Return exact Telegram chat ID only.

        message_thread_id_override_prompt:
          name: Message Thread ID Override Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional.
            Use only when user specifies another topic.
            Return numeric thread ID only.

mode: queued
max: 30
max_exceeded: silent

variables:
  version: 20251116

fields:
  summary:
    name: Summary
    description: !input summary_prompt
    selector:
      text:
    required: true

  detail:
    name: Detail
    description: !input detail_prompt
    selector:
      text:

  content_type:
    name: Content Type
    description: !input content_type_prompt
    selector:
      select:
        options:
          - information
          - location
          - image
    required: true

  location:
    name: Location
    description: !input location_prompt
    selector:
      text:

  image_path:
    name: Image Path
    description: !input image_path_prompt
    selector:
      text:

  target_chat_id:
    name: Override Chat ID
    description: !input chat_id_override_prompt
    selector:
      text:

  target_message_thread_id:
    name: Override Thread ID
    description: !input message_thread_id_override_prompt
    selector:
      text:

sequence:
  - variables:
      default_chat_id: !input chat_id
      default_thread_id: !input thread_id
      delete_after_send: !input delete_after_send

      summary: "{{ summary | trim }}"
      detail: "{{ detail | default('') | trim }}"
      content_type: "{{ content_type | trim }}"
      location: "{{ location | default('') | trim }}"
      image_path: "{{ image_path | default('') | trim }}"

      override_chat_id: "{{ target_chat_id | default('') | trim }}"
      override_message_thread_id: "{{ target_message_thread_id | default('') | trim }}"

      chat_id_value: >-
        {% set c = override_chat_id if override_chat_id else default_chat_id %}
        {{ c | string | trim if c else '' }}

      message_thread_id_value: >-
        {% if override_message_thread_id %}
          {{ override_message_thread_id }}
        {% elif default_thread_id is not none %}
          {{ (default_thread_id | string) | trim }}
        {% else %}
          {{ '' }}
        {% endif %}

      image_path_resolved: >-
        {% if image_path.startswith('local/') %}
          {{ '/media/' ~ image_path[6:] }}
        {% else %}
          {{ image_path }}
        {% endif %}

  - alias: Validate inputs
    if:
      - condition: template
        value_template: >-
          {{
            not summary
            or content_type not in ['information','location','image']
            or not chat_id_value
            or (content_type == 'location' and not location)
            or (content_type == 'image' and not image_path)
            or (
              override_message_thread_id
              and not override_message_thread_id | regex_match('^\d+$')
            )
          }}
    then:
      - stop: Invalid input for sending Telegram message.

  - choose:
      - conditions: "{{ content_type == 'information' }}"
        sequence:
          - action: pyscript.send_telegram_message
            data:
              chat_id: "{{ chat_id_value }}"
              message_thread_id: "{{ message_thread_id_value }}"
              parse_mode: HTML
              message: |-
                <b>{{ summary | e }}</b>{% if detail %}

                {{ detail | e }}{% endif %}

                {% set q = summary.split() | join('+') %}
                <a href="https://www.google.com/search?q={{ q }}">Google Search</a>
            response_variable: telegram_response

      - conditions: "{{ content_type == 'location' }}"
        sequence:
          - action: pyscript.send_telegram_message
            data:
              chat_id: "{{ chat_id_value }}"
              message_thread_id: "{{ message_thread_id_value }}"
              parse_mode: HTML
              message: |-
                <b>{{ summary | e }}</b>{% if detail %}

                {{ detail | e }}{% endif %}

                {% set p = (summary ~ ' ' ~ location).split() | join('+') %}
                <a href="https://www.google.com/maps/search/?api=1&query={{ p }}">Google Maps</a>
            response_variable: telegram_response

      - conditions: "{{ content_type == 'image' }}"
        sequence:
          - action: pyscript.send_telegram_photo
            data:
              chat_id: "{{ chat_id_value }}"
              message_thread_id: "{{ message_thread_id_value }}"
              parse_mode: HTML
              file_path: "{{ image_path_resolved }}"
              caption: |-
                <b>{{ summary | e }}</b>{% if detail %}

                {{ detail | e }}{% endif %}
            response_variable: telegram_response

          - if:
              - condition: template
                value_template: "{{ delete_after_send }}"
            then:
              - action: delete.file
                data:
                  file: "{{ image_path_resolved }}"

  - stop: ""
    response_variable: telegram_response
