blueprint:
  name: Voice - Send to Zalo
  author: luuquangvu + merge by ChatGPT
  source_url: https://github.com/luuquangvu/tutorials/blob/main/send_to_zalo_bot_full_llm.yaml
  description: |-
    Tool for sending content to Zalo used for Voice Assistant.
    Supports information, location, and image.
    Automatically resolves local/ image paths and deletes images after sending.
  domain: script
  homeassistant:
    min_version: 2024.10.0

  input:
    zalo_settings:
      name: Settings for Zalo
      icon: mdi:alpha-z-circle-outline
      input:
        chat_id:
          name: Chat ID
          selector:
            text:

    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      collapsed: true
      input:
        summary_prompt:
          name: Summary Prompt
          selector:
            text:
              multiline: true
          default: |-
            This argument is mandatory and must always be included.
            Provide a short summary (<=10 words). No markdown, emojis or commentary.
            If content_type is image, write a concise caption.
            Return only plain text.

        detail_prompt:
          name: Detail Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional detailed information.
            No links, no markdown/emojis, do not repeat the summary.
            Return only plain text.

        content_type_prompt:
          name: Content Type Prompt
          selector:
            text:
              multiline: true
          default: |-
            Mandatory.
            Return exactly one: information, location, image.
            Choose location for places/maps.
            Choose image when sending a photo with a path.
            Otherwise choose information.

        location_prompt:
          name: Location Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional. Use only when content_type is location.
            Return address name only. No punctuation.

        image_path_prompt:
          name: Image Path Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional. Use only when content_type is image.
            Provide existing local/ or /media/ image path.
            Do not guess.

        chat_id_override_prompt:
          name: Chat ID Override Prompt
          selector:
            text:
              multiline: true
          default: |-
            Optional. Use only when user explicitly specifies another chat.
            Return exact Zalo chat ID only.

mode: queued
max: 30
max_exceeded: silent

variables:
  version: 20251116

fields:
  summary:
    name: Summary
    description: !input summary_prompt
    selector:
      text:
    required: true

  detail:
    name: Detail
    description: !input detail_prompt
    selector:
      text:

  content_type:
    name: Content Type
    description: !input content_type_prompt
    selector:
      select:
        options:
          - information
          - location
          - image
    required: true

  location:
    name: Location
    description: !input location_prompt
    selector:
      text:

  image_path:
    name: Image Path
    description: !input image_path_prompt
    selector:
      text:

  target_chat_id:
    name: Override Chat ID
    description: !input chat_id_override_prompt
    selector:
      text:

sequence:
  - variables:
      default_chat_id: !input chat_id
      summary: "{{ summary | trim }}"
      detail: "{{ detail | default('') | trim }}"
      content_type: "{{ content_type | trim }}"
      location: "{{ location | default('') | trim }}"
      image_path: "{{ image_path | default('') | trim }}"
      override_chat_id: "{{ target_chat_id | default('') | trim }}"
      chat_id_value: >-
        {% set c = override_chat_id if override_chat_id else default_chat_id %}
        {{ c | string | trim if c else '' }}

      image_path_resolved: >-
        {% if image_path.startswith('local/') %}
          {{ '/media/' ~ image_path[6:] }}
        {% else %}
          {{ image_path }}
        {% endif %}

  - alias: Validate inputs
    if:
      - condition: template
        value_template: >-
          {{
            not summary
            or content_type not in ['information','location','image']
            or not chat_id_value
            or (content_type == 'location' and not location)
            or (content_type == 'image' and not image_path)
          }}
    then:
      - stop: Invalid input for sending Zalo message.

  - choose:
      - conditions: "{{ content_type == 'information' }}"
        sequence:
          - action: pyscript.send_zalo_message
            data:
              chat_id: "{{ chat_id_value }}"
              message: |-
                {{ summary }}{% if detail %}

                {{ detail }}{% endif %}

                {% set q = summary.split() | join('+') %}
                Google Search (https://www.google.com/search?q={{ q }})
            response_variable: zalo_response

      - conditions: "{{ content_type == 'location' }}"
        sequence:
          - action: pyscript.send_zalo_message
            data:
              chat_id: "{{ chat_id_value }}"
              message: |-
                {{ summary }}{% if detail %}

                {{ detail }}{% endif %}

                {% set p = (summary ~ ' ' ~ location).split() | join('+') %}
                Google Maps (https://www.google.com/maps/search/?api=1&query={{ p }})
            response_variable: zalo_response

      - conditions: "{{ content_type == 'image' }}"
        sequence:
          - action: pyscript.send_zalo_photo
            data:
              chat_id: "{{ chat_id_value }}"
              file_path: "{{ image_path_resolved }}"
              caption: |-
                {{ summary }}{% if detail %}

                {{ detail }}{% endif %}
            response_variable: zalo_response

          - action: delete.file
            data:
              file: "{{ image_path_resolved }}"

  - stop: ""
    response_variable: zalo_response
