blueprint:
  name: Universal Cooldown Recovery
  author: TriTue2011
  source_url: https://github.com/TriTue2011/Blueprint/blob/main/universal_cooldown_recovery.yaml
  description: >
    Khi entity chuyển trạng thái theo cấu hình:
      - Start Timer Helper
      - Lưu thời điểm hết hạn
      - Tự phục hồi sau restart hoặc mất điện
      - Khi hết thời gian sẽ thực hiện action tùy chỉnh

  domain: automation

  homeassistant:
    min_version: 2024.10.0

  input:

    trigger_entity:
      name: Trigger Entity
      selector:
        entity: {}

    from_state:
      name: From State
      default: "on"
      selector:
        text: {}

    to_state:
      name: To State
      default: "off"
      selector:
        text: {}

    timer_entity:
      name: Timer Helper
      selector:
        entity:
          filter:
            - domain: timer

    end_time_helper:
      name: End Time Helper
      description: Input Datetime lưu thời điểm hết hạn
      selector:
        entity:
          filter:
            - domain: input_datetime

    finish_actions:
      name: Actions When Finished
      selector:
        action: {}

mode: single

variables:

  timer_entity: !input timer_entity
  end_time_helper: !input end_time_helper

trigger:

  - id: start_timer
    trigger: state
    entity_id: !input trigger_entity
    from: !input from_state
    to: !input to_state

  - id: timer_finished
    trigger: event
    event_type: timer.finished

  - id: ha_start
    trigger: homeassistant
    event: start

action:

  - choose:

      #
      # START TIMER
      #
      - conditions:
          - condition: trigger
            id: start_timer

        sequence:

          - variables:
              duration: >
                {{ state_attr(timer_entity, 'duration') }}

          - action: input_datetime.set_datetime
            target:
              entity_id: !input end_time_helper
            data:
              datetime: >
                {% set sec = duration | as_timedelta %}
                {{ (now() + sec).strftime('%Y-%m-%d %H:%M:%S') }}

          - action: timer.start
            target:
              entity_id: !input timer_entity

      #
      # TIMER FINISHED
      #
      - conditions:

          - condition: trigger
            id: timer_finished

          - condition: template
            value_template: >
              {{ trigger.event.data.entity_id == timer_entity }}

        sequence:

          - action: input_datetime.set_datetime
            target:
              entity_id: !input end_time_helper
            data:
              datetime: "1970-01-01 00:00:00"

          - sequence: !input finish_actions

      #
      # RECOVERY AFTER RESTART
      #
      - conditions:

          - condition: trigger
            id: ha_start

          - condition: template
            value_template: >
              {{
                states(end_time_helper)
                not in ['unknown','unavailable','']
              }}

          - condition: template
            value_template: >
              {{
                states(end_time_helper)
                != '1970-01-01 00:00:00'
              }}

          - condition: template
            value_template: >
              {{
                now() >=
                states(end_time_helper)|as_datetime
              }}

        sequence:

          - action: input_datetime.set_datetime
            target:
              entity_id: !input end_time_helper
            data:
              datetime: "1970-01-01 00:00:00"

          - sequence: !input finish_actions
