blueprint:
  name: Voice - Smart Camera AI Analyzer (Auto)
  author: luuquangvu_benbap
  description: |
    Smart AI-powered camera analysis script (auto)
    - Không cần cấu hình danh sách camera thủ công
    - Tự lấy toàn bộ camera thật trong Home Assistant
    - Ưu tiên match friendly_name
    - Nếu không khớp thì match theo sensor aliases (giống blueprint Capture Camera Snapshot)
    - Nếu vẫn không khớp thì đoán theo từ khóa ("phòng khách", "ban công", "cửa")
    - Trả lời tiếng Việt, prompt tiếng Anh
    - Hỗ trợ structure (overview, cameras_with_people, cameras_no_people, cameras_error, summary)
  domain: script
  homeassistant:
    min_version: 2025.8.0

  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: Sensor alias giống blueprint Capture Camera Snapshot
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
                - domain:
                    - sensor
                  integration: template
              multiple: false

    ai_task_settings:
      name: AI Task Settings
      icon: mdi:robot-outline
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          description: Leave empty to use system default AI Task
          selector:
            entity:
              filter:
                - domain:
                    - ai_task
              multiple: false
          default:

    prompt_settings:
      name: Prompt Settings
      icon: mdi:robot
      collapsed: true
      input:
        system_prompt:
          name: System Prompt (English)
          description: Main instructions for the LLM
          selector:
            text:
              multiline: true
          default: |
            You are an AI assistant for a Home Assistant smart home system. You analyze live camera streams.

            IMPORTANT CONTEXT:
            - The user may ask you to:
              * Detect people, pets, or motion
              * Check if the camera is online/offline
              * Describe what is seen in the image (objects, people, pets, background)
            - You are called from a script that may send you ONE or MULTIPLE cameras.
            - You MUST base your answer ONLY on the attached media.
            - You MUST answer IN VIETNAMESE with proper diacritics.

            USER QUESTION:
            "{user_question}"

            AVAILABLE CAMERAS:
            {camera_list}

            ### MODES
            1. DESCRIBE MODE (when user says “có những gì”, “thấy gì”, “bên trong có gì”)
               - Describe EVERYTHING visible in the frame: people, pets (cat/dog), vehicles, objects, doors, background, lighting.
               - Do NOT limit to people.
               - Output should be short, clear, natural Vietnamese.
            2. DETECTION MODE (when user says “có người không”, “có mèo không”, “có ai không”)
               - Focus on target the user asked (person/pet).
               - If not seen → say clearly “Không thấy …”.
               - Keep it short for TTS.
            3. MULTI-CAMERA MODE (when user says “camera nào”, “tất cả camera”, “kiểm tra tất cả”)
               - You will receive MULTIPLE camera attachments.
               - You MUST return structured data:
                 * overview: short description of all cameras
                 * cameras_with_people: cameras where you SEE people
                 * cameras_no_people: cameras where you see NO people
                 * cameras_error: cameras dark/blocked/offline
                 * summary: ONE Vietnamese sentence ≤ 120 chars for TTS
            DETECTION RULES:
            - “Có người” = any visible human.
            - If user asked about pets, prioritize cats/dogs over people.
            - If the frame is too dark/blurred → say so, do not guess.
            - Do NOT describe fixed walls/furniture unless needed for location.
            OUTPUT RULES:
            - Always in Vietnamese.
            - If structure is provided, fill ALL required fields.
            - No Markdown, no code blocks.
            - Do NOT invent unseen cameras or content.
            SUMMARY FIELD:
            - One short Vietnamese sentence

mode: parallel
max_exceeded: silent

variables:
  version: 20251031_auto_alias_nocamselect

fields:
  instructions:
    name: Camera Question
    description: Hỏi bất kỳ về camera
    selector:
      text:
        multiline: true
    required: true

sequence:
  # 1. Lấy biến đầu vào
  - variables:
      entity_aliases: !input entity_aliases
      ai_task_entity: !input ai_task_entity
      system_prompt: !input system_prompt
      user_question: "{{ instructions | default('') | trim }}"

  # 2. Kiểm tra câu hỏi rỗng
  - if:
      - condition: template
        value_template: "{{ not user_question }}"
    then:
      - variables:
          response:
            error: "Please provide a question about cameras."
      - stop: "Missing question"
        response_variable: response

  # 3. Lấy toàn bộ camera trong hệ thống
  - variables:
      all_cameras: >
        {% set cams = states.camera | map(attribute='entity_id') | list %}
        {{ cams }}
      camera_list_text: >
        {% set ns = namespace(list=[]) %}
        {% for cam in all_cameras %}
          {% set name = state_attr(cam, 'friendly_name') or cam %}
          {% set ns.list = ns.list + ['- ' ~ name ~ ' (' ~ cam ~ ')'] %}
        {% endfor %}
        {{ ns.list | join('\n') }}
      user_question_lc: "{{ user_question | lower }}"

  # 4. Tự động dò camera
  - variables:
      matched_camera_from_friendly: >
        {% set q = user_question | trim %}
        {% set found = '' %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') or '') | trim %}
          {% if fn and (fn | lower) == (q | lower) %}
            {% set found = cam %}
          {% elif fn and (q | lower) in (fn | lower) %}
            {% if not found %}
              {% set found = cam %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ found }}

      matched_camera_from_alias: >
        {% set entities = state_attr(entity_aliases, 'entities') | default([]) %}
        {% set ql = user_question_lc %}
        {% set found = '' %}
        {% for item in entities %}
          {% set eid = item.entity_id %}
          {% set als = item.aliases | default([]) %}
          {% if 'camera.' in eid %}
            {% for a in als %}
              {% if (a | lower) == ql or (ql in (a | lower)) %}
                {% set found = eid %}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}
        {{ found }}

      guessed_camera_hardcode: >
        {% if 'phòng khách' in user_question_lc %}
          {% for cam in all_cameras %}
            {% if 'phòng khách' in (state_attr(cam, 'friendly_name') | default('') | lower) %}
              {{ cam }}
            {% endif %}
          {% endfor %}
        {% elif 'ban công' in user_question_lc %}
          {% for cam in all_cameras %}
            {% if 'ban công' in (state_attr(cam, 'friendly_name') | default('') | lower) %}
              {{ cam }}
            {% endif %}
          {% endfor %}
        {% elif 'cửa' in user_question_lc %}
          {% for cam in all_cameras %}
            {% if 'cửa' in (state_attr(cam, 'friendly_name') | default('') | lower) %}
              {{ cam }}
            {% endif %}
          {% endfor %}
        {% else %}
          {{ '' }}
        {% endif %}

      fallback_camera: >
        {% if all_cameras | length > 0 %}
          {{ all_cameras[0] }}
        {% else %}
          {{ '' }}
        {% endif %}

      final_single_camera: >
        {% if matched_camera_from_friendly %}
          {{ matched_camera_from_friendly }}
        {% elif matched_camera_from_alias %}
          {{ matched_camera_from_alias }}
        {% elif guessed_camera_hardcode %}
          {{ guessed_camera_hardcode }}
        {% else %}
          {{ fallback_camera }}
        {% endif %}

      use_single_camera: >
        {% set q = user_question_lc %}
        {% if 'tất cả' in q
              or 'all camera' in q
              or 'camera nào' in q
              or 'những camera' in q
              or 'các camera' in q
              or 'which cameras' in q
              or 'check all' in q %}
          false
        {% else %}
          true
        {% endif %}

  # 5. Xây danh sách đính kèm camera
  - variables:
      single_attachment: >
        {
          "media_content_id": "media-source://camera/{{ final_single_camera }}",
          "media_content_type": "application/vnd.apple.mpegurl",
          "metadata": {
            "title": "{{ state_attr(final_single_camera, 'friendly_name') or final_single_camera }}",
            "thumbnail": "/api/camera_proxy/{{ final_single_camera }}",
            "media_class": "video"
          }
        }
      all_attachments: >
        {% set ns = namespace(items=[]) %}
        {% for cam in all_cameras %}
          {% if states(cam) is not none %}
            {% set name = state_attr(cam, 'friendly_name') or cam %}
            {% set item = {
              'media_content_id': 'media-source://camera/' ~ cam,
              'media_content_type': 'application/vnd.apple.mpegurl',
              'metadata': {
                'title': name,
                'thumbnail': '/api/camera_proxy/' ~ cam,
                'media_class': 'video'
              }
            } %}
            {% set ns.items = ns.items + [item] %}
          {% endif %}
        {% endfor %}
        {{ ns.items }}
      camera_count: "{{ all_cameras | length }}"

  # 6. Build prompt cuối
  - variables:
      final_prompt: >
        {{ system_prompt
           | replace('{camera_list}', camera_list_text)
           | replace('{user_question}', user_question) }}

  # 7. Gọi AI task
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ not ai_task_entity }}"
        sequence:
          - action: ai_task.generate_data
            data:
              task_name: "Smart Camera Analysis"
              instructions: "{{ final_prompt }}"
              attachments: >
                {% if use_single_camera %}
                  {{ [single_attachment] }}
                {% else %}
                  {{ all_attachments }}
                {% endif %}
              structure:
                overview:
                  description: "Short status of all cameras"
                  required: true
                  selector:
                    text: {}
                cameras_with_people:
                  description: "List of cameras with people"
                  required: true
                  selector:
                    text: {}
                cameras_no_people:
                  description: "List of cameras without people"
                  required: true
                  selector:
                    text: {}
                cameras_error:
                  description: "List of cameras with errors"
                  required: true
                  selector:
                    text: {}
                summary:
                  description: "One sentence summary in Vietnamese"
                  required: true
                  selector:
                    text: {}
            response_variable: ai_result
      - conditions:
          - condition: template
            value_template: "{{ ai_task_entity is not none }}"
        sequence:
          - action: ai_task.generate_data
            data:
              entity_id: "{{ ai_task_entity }}"
              task_name: "Smart Camera Analysis"
              instructions: "{{ final_prompt }}"
              attachments: >
                {% if use_single_camera %}
                  {{ [single_attachment] }}
                {% else %}
                  {{ all_attachments }}
                {% endif %}
              structure:
                overview:
                  description: "Short status of all cameras"
                  required: true
                  selector:
                    text: {}
                cameras_with_people:
                  description: "List of cameras with people"
                  required: true
                  selector:
                    text: {}
                cameras_no_people:
                  description: "List of cameras without people"
                  required: true
                  selector:
                    text: {}
                cameras_error:
                  description: "List of cameras with errors"
                  required: true
                  selector:
                    text: {}
                summary:
                  description: "One sentence summary in Vietnamese"
                  required: true
                  selector:
                    text: {}
            response_variable: ai_result

  # 8. Trả kết quả + debug
  - variables:
      response:
        mode: "{{ 'single' if use_single_camera else 'multi' }}"
        camera_count: "{{ camera_count }}"
        selected_camera: "{{ final_single_camera }}"
        matched_camera_from_friendly: "{{ matched_camera_from_friendly }}"
        matched_camera_from_alias: "{{ matched_camera_from_alias }}"
        guessed_camera_hardcode: "{{ guessed_camera_hardcode }}"
        data: "{{ ai_result.data }}"
  - stop: ""
    response_variable: response
