blueprint:
  name: Voice - Smart Camera Analyzer (Single + Sequential)
  author: benbap_fixed
  description: |
    Tự động phát hiện:
    - Hỏi 1 camera → Trả lời trực tiếp
    - Hỏi nhiều camera → Phân tích tuần tự rồi tổng hợp
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
              - domain:
                - sensor
                integration: template
              multiple: false
          default:
    
    ai_task_settings:
      name: AI Task Settings
      icon: mdi:robot-outline
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity
          selector:
            entity:
              filter:
              - domain:
                - ai_task
              multiple: false
          default:
        
        delay_between_cameras:
          name: Delay Between Cameras (seconds)
          description: Chỉ dùng khi phân tích nhiều camera
          selector:
            number:
              min: 0
              max: 10
              step: 0.5
              unit_of_measurement: s
          default: 1

mode: parallel
max_exceeded: silent

fields:
  instructions:
    name: Camera Question
    description: Hỏi về camera (VD "camera phòng khách có người không", "tất cả camera thấy gì")
    selector:
      text:
        multiline: true
    required: true

sequence:
  # ===== BƯỚC 1: LẤY BIẾN =====
  - variables:
      entity_aliases: !input entity_aliases
      ai_task_entity: !input ai_task_entity
      delay_between_cameras: !input delay_between_cameras
      user_question: '{{ instructions | default("") | trim }}'
  
  - if:
    - condition: template
      value_template: '{{ not user_question }}'
    then:
    - variables:
        response:
          error: "Vui lòng nhập câu hỏi"
    - stop: Missing question
      response_variable: response
  
  # ===== BƯỚC 2: LẤY DANH SÁCH CAMERA =====
  - variables:
      all_cameras: >-
        {% set cams = states.camera 
           | selectattr('state', 'in', ['idle', 'streaming', 'recording'])
           | map(attribute='entity_id') 
           | list %}
        {{ cams }}
      
      user_question_lc: '{{ user_question | lower }}'
  
  # ===== BƯỚC 3: XÁC ĐỊNH MODE (SINGLE vs MULTI) =====
  - variables:
      # Kiểm tra từ khóa multi-camera
      is_multi_camera_request: >-
        {% set q = user_question_lc %}
        {{ 'tất cả' in q
           or 'all camera' in q
           or 'camera nào' in q
           or 'những camera' in q
           or 'các camera' in q
           or 'which cameras' in q
           or 'check all' in q
           or 'toàn bộ' in q }}
      
      # Match camera từ friendly_name
      matched_camera_from_friendly: >-
        {% set q = user_question | trim %}
        {% set found = '' %}
        {% for cam in all_cameras %}
          {% set fn = (state_attr(cam, 'friendly_name') or '') | trim %}
          {% if fn and (fn | lower) == (q | lower) %}
            {% set found = cam %}
          {% elif fn and (q | lower) in (fn | lower) %}
            {% if not found %}
              {% set found = cam %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ found }}
      
      # Match camera từ aliases
      matched_camera_from_alias: >-
        {% set entities = state_attr(entity_aliases, 'entities') | default([]) %}
        {% set ql = user_question_lc %}
        {% set found = '' %}
        {% for item in entities %}
          {% set eid = item.entity_id %}
          {% set als = item.aliases | default([]) %}
          {% if 'camera.' in eid %}
            {% for a in als %}
              {% if (a | lower) == ql or (ql in (a | lower)) %}
                {% set found = eid %}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}
        {{ found }}
      
      # Đoán camera theo từ khóa
      guessed_camera: >-
        {% if 'phòng khách' in user_question_lc %}
          {% for cam in all_cameras %}
            {% if 'phòng khách' in (state_attr(cam, 'friendly_name') | default('') | lower) %}
              {{ cam }}
            {% endif %}
          {% endfor %}
        {% elif 'ban công' in user_question_lc %}
          {% for cam in all_cameras %}
            {% if 'ban công' in (state_attr(cam, 'friendly_name') | default('') | lower) %}
              {{ cam }}
            {% endif %}
          {% endfor %}
        {% elif 'cửa' in user_question_lc %}
          {% for cam in all_cameras %}
            {% if 'cửa' in (state_attr(cam, 'friendly_name') | default('') | lower) %}
              {{ cam }}
            {% endif %}
          {% endfor %}
        {% else %}
          {{ '' }}
        {% endif %}
      
      # Camera cuối cùng được chọn (nếu single mode)
      final_camera: >-
        {% if matched_camera_from_friendly %}
          {{ matched_camera_from_friendly }}
        {% elif matched_camera_from_alias %}
          {{ matched_camera_from_alias }}
        {% elif guessed_camera %}
          {{ guessed_camera }}
        {% else %}
          {{ '' }}
        {% endif %}
      
      # Quyết định mode
      use_mode: >-
        {% if is_multi_camera_request %}
          multi
        {% elif final_camera %}
          single
        {% else %}
          multi
        {% endif %}
  
  # ===== BƯỚC 4: XỬ LÝ THEO MODE =====
  - choose:
    
    # ========== MODE: SINGLE CAMERA ==========
    - conditions:
      - condition: template
        value_template: '{{ use_mode == "single" }}'
      sequence:
        - variables:
            camera_name: '{{ state_attr(final_camera, "friendly_name") or final_camera }}'
            single_prompt: >-
              You are analyzing a single camera frame.
              
              CAMERA: {{ camera_name }}
              USER QUESTION: "{{ user_question }}"
              
              INSTRUCTIONS:
              - Answer in VIETNAMESE with proper diacritics
              - Be conversational and natural (2-3 sentences max)
              - If asked about people: "Có người" or "Không có người"
              - If asked to describe: mention main visible elements
              - If dark/blocked: "Camera bị tối/che khuất"
              
              Answer directly, no extra formatting.
            
            camera_attachment:
              media_content_id: 'media-source://camera/{{ final_camera }}'
              media_content_type: 'image/jpeg'
              metadata:
                title: '{{ camera_name }}'
                media_class: 'image'
        
        # Gọi AI
        - choose:
          - conditions:
            - condition: template
              value_template: '{{ not ai_task_entity }}'
            sequence:
            - action: ai_task.generate_data
              data:
                task_name: 'Analyze {{ camera_name }}'
                instructions: '{{ single_prompt }}'
                attachments: 
                  - '{{ camera_attachment }}'
              response_variable: ai_result
          
          default:
          - action: ai_task.generate_data
            data:
              entity_id: '{{ ai_task_entity }}'
              task_name: 'Analyze {{ camera_name }}'
              instructions: '{{ single_prompt }}'
              attachments:
                - '{{ camera_attachment }}'
            response_variable: ai_result
        
        # Trả kết quả
        - variables:
            response:
              mode: 'single'
              camera: '{{ final_camera }}'
              camera_name: '{{ camera_name }}'
              answer: '{{ ai_result.data if ai_result.data is defined else "Lỗi phân tích" }}'
              timestamp: '{{ now().isoformat() }}'
        
        - stop: ''
          response_variable: response
    
    # ========== MODE: MULTI CAMERA (SEQUENTIAL) ==========
    - conditions:
      - condition: template
        value_template: '{{ use_mode == "multi" }}'
      sequence:
        # Kiểm tra có camera không
        - if:
          - condition: template
            value_template: '{{ all_cameras | length == 0 }}'
          then:
          - variables:
              response:
                error: "Không tìm thấy camera nào"
          - stop: No cameras
            response_variable: response
        
        # Chuẩn bị prompt
        - variables:
            analysis_prompt: >-
              Analyze this single camera frame.
              
              USER QUESTION: "{{ user_question }}"
              
              Answer in VIETNAMESE (1-2 sentences):
              - People detection: "Có người" or "Không có người"
              - Description: main objects/people/pets
              - Issues: "Camera tối/che khuất" if applicable
            
            camera_results: []
        
        # Loop qua từng camera
        - repeat:
            for_each: '{{ all_cameras }}'
            sequence:
              - variables:
                  current_camera: '{{ repeat.item }}'
                  camera_name: '{{ state_attr(repeat.item, "friendly_name") or repeat.item }}'
              
              - variables:
                  camera_attachment:
                    media_content_id: 'media-source://camera/{{ current_camera }}'
                    media_content_type: 'image/jpeg'
                    metadata:
                      title: '{{ camera_name }}'
                      media_class: 'image'
              
              # Gọi AI phân tích
              - choose:
                - conditions:
                  - condition: template
                    value_template: '{{ not ai_task_entity }}'
                  sequence:
                  - action: ai_task.generate_data
                    data:
                      task_name: 'Analyze {{ camera_name }}'
                      instructions: '{{ analysis_prompt }}'
                      attachments: 
                        - '{{ camera_attachment }}'
                    response_variable: ai_single_result
                
                default:
                - action: ai_task.generate_data
                  data:
                    entity_id: '{{ ai_task_entity }}'
                    task_name: 'Analyze {{ camera_name }}'
                    instructions: '{{ analysis_prompt }}'
                    attachments:
                      - '{{ camera_attachment }}'
                  response_variable: ai_single_result
              
              # Lưu kết quả
              - variables:
                  camera_results: >-
                    {% set results = camera_results %}
                    {% set new_result = {
                      'camera': current_camera,
                      'camera_name': camera_name,
                      'analysis': ai_single_result.data if ai_single_result.data is defined else 'Lỗi',
                      'timestamp': now().isoformat()
                    } %}
                    {{ results + [new_result] }}
              
              # Delay
              - if:
                - condition: template
                  value_template: '{{ repeat.index < all_cameras | length }}'
                then:
                - delay:
                    seconds: '{{ delay_between_cameras }}'
        
        # Tổng hợp kết quả
        - variables:
            summary_prompt: >-
              Summarize these camera analysis results in Vietnamese.
              
              USER QUESTION: "{{ user_question }}"
              
              RESULTS:
              {% for result in camera_results %}
              - {{ result.camera_name }}: {{ result.analysis }}
              {% endfor %}
              
              Create a natural 2-4 sentence summary:
              - If asked about people: list cameras WITH people, then WITHOUT
              - If asked to describe: overview of what's visible
              - Keep it conversational for voice assistant
        
        - choose:
          - conditions:
            - condition: template
              value_template: '{{ not ai_task_entity }}'
            sequence:
            - action: ai_task.generate_data
              data:
                task_name: 'Summary'
                instructions: '{{ summary_prompt }}'
              response_variable: ai_summary_result
          
          default:
          - action: ai_task.generate_data
            data:
              entity_id: '{{ ai_task_entity }}'
              task_name: 'Summary'
              instructions: '{{ summary_prompt }}'
            response_variable: ai_summary_result
        
        # Trả kết quả
        - variables:
            response:
              mode: 'multi'
              camera_count: '{{ all_cameras | length }}'
              individual_results: '{{ camera_results }}'
              summary: '{{ ai_summary_result.data if ai_summary_result.data is defined else "Không tổng hợp được" }}'
              timestamp: '{{ now().isoformat() }}'
        
        - stop: ''
          response_variable: response
