_pyscript_sync_dir="/config/pyscript"
_pyscript_sync_manifest="${_pyscript_sync_dir}/_sources.txt"
_pyscript_sync_auto_update="false"   # false = chỉ check
_pyscript_sync_token=""              # để trống nếu public repo
_pyscript_sync_reload="true"
_pyscript_sync_curl_options="--silent"
_pyscript_sync_debug="false"
